### ISSUE TITLE
Build wheels for RTModel package

### ISSUE THREAD

**Issue by ketozhang** [valboz/RTModel#13]
@golmschenk @valboz 

Currently it takes about 2+ minutes to install RTModel because it, VBBinaryLensing, and VBMicrolensing is not pre-compiled. 

```
00:06:05.049    Building wheel for RTModel (pyproject.toml): started
00:06:51.618    Building wheel for RTModel (pyproject.toml): finished with status 'done'
00:06:51.618    Created wheel for RTModel: filename=rtmodel-2.2-cp311-cp311-manylinux_2_36_x86_64.whl size=939897 sha256=ed162c7023df022b2a2b6180099da41b597f0d8ce7d7b2fa5a66923c871c8e4a
00:06:51.618    Stored in directory: /root/.cache/pip/wheels/07/84/6f/c9bcff61443e22406176fedc40cfa84e4d5ea8966b4170c755
00:06:51.618    Building wheel for VBBinaryLensing (pyproject.toml): started
00:07:30.175    Building wheel for VBBinaryLensing (pyproject.toml): finished with status 'done'
00:07:30.175    Created wheel for VBBinaryLensing: filename=VBBinaryLensing-3.7.0-cp311-cp311-linux_x86_64.whl size=2755930 sha256=bff0ab53a905e0668f643839ea151e728dfe585ea29fc1e516b9143b22c4788d
00:07:30.175    Stored in directory: /root/.cache/pip/wheels/86/0f/26/c7acb53f37c0707b6b071aec387ca07aa57953b614d2c33e89
00:07:30.175    Building wheel for VBMicrolensing (pyproject.toml): started
00:08:26.247    Building wheel for VBMicrolensing (pyproject.toml): finished with status 'done'
00:08:26.247    Created wheel for VBMicrolensing: filename=VBMicrolensing-4.1.0-cp311-cp311-linux_x86_64.whl size=3125032 sha256=50c3fd5edf0608bfde6ee2f30d0191092341613b307f29f7d41a3c4e8b678159
```

In Python you can pre-compile source code (including C++) as wheel files and upload them to PyPI.

**Comment by ketozhang** [comment]
Ah this is because I am also installing pyLIMA which does use VBBinaryLensing.

@valboz We run this install 10+ times per week, so this may save us over an hour. This would be much appreciated!

**Comment by golmschenk** [comment]
@valboz, as one possible option, you can consider using [cibuildwheel](https://cibuildwheel.pypa.io/en/stable/). This is the package I use to have the GitHub CI runners automatically precompile wheels for all major operating systems and Python versions for `eesunhong`. It's made by a team that overlaps with the team that makes `scikit-build-core`, the framework I added to RTModel to use the CMake build method. So the two frameworks have pretty good integration with one another. Just an option!

**Comment by valboz** [comment]
Thanks @golmschenk . I already read about it some time ago. It looks a very good idea!

**Comment by ketozhang** [comment]
Here's a very good reference GitHub Actions workflow file from the cibuildwheel authors themselves.

https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

**Comment by ketozhang** [comment]
Thanks Valerio it's working well on Linux. I'd love to also have this done for VBBinaryLensing if possible.

Note that wheels for MacOS x86 is missing (non-ARM).

**Comment by valboz** [comment]
Hi, now also wheels for MacOS x86 are available.
I will add wheels to VBMicrolensing in the next few days.
I think I can close this issue now.
Thanks for raising this point and for your help!
