### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/RTModel/bin/Reader'

### ISSUE THREAD

**Issue by Atousa-Kalantari** [valboz/RTModel#2]
I encountered an issue while running the following part: `rtm.run()`. The error message I received is as follows:

FileNotFoundError: [Errno 2] No such file or directory: ‘/usr/local/lib/python3.10/dist-packages/RTModel/bin/Reader’

Could you please guide me on how to resolve this?

**Comment by valboz** [comment]
Hi, thank you for trying RTModel. 

Have you installed by "pip install RTModel" or by cloning the GitHub repository? The version in the repository is more cross-platform and should work on more systems.
Which system are you using?

**Comment by Atousa-Kalantari** [comment]
Hi,

Yes, I have tried both methods of installation: using pip install and by
cloning the GitHub repository. Unfortunately, I have not been successful
with either method on my system, which is macOS.

In addition to this, I also attempted to run it in Google Colab and
installed it there using pip. However, I encountered the same error in
Colab as well.

**Comment by golmschenk** [comment]
Hi @Atousa-Kalantari, could you try installing it via `pip install -U git+https://github.com/golmschenk/RTModel@cross_platform_build_missing_site_packages_fix`? This will install a branch I have with a potential fix. I have tested it on macOS and Colab, and, at least with my environment, it works for both these cases. Please let me know if this fails in any of your cases.

@valboz, this implements the fix I recommended in [this comment](https://github.com/valboz/RTModel/pull/1#issuecomment-2041817057), which I was hoping would fix the issue with my version you were seeing on the Windows install. Assuming this works for @Atousa-Kalantari, please let me know if it works for the setup you had previously see the site-packages install version failing on before. If it does, I will ask for more information to find out why.

**Comment by Atousa-Kalantari** [comment]
@golmschenk 
Hi, I just wanted to let you know that it worked perfectly for both macOS and Colab. Thank you so much for your help!

**Comment by valboz** [comment]
@golmschenk I just checked that it also worked for me! Thanks
